--Drop ARTICLE_COLOR_LOOKUP FK
ALTER TABLE SHOP_FACTS
DROP CONSTRAINT FK_SHOP_FACTS_ARTICLE_COLOR_LOOKUP;

--Drop ARTICLE_LOOKUP FK
ALTER TABLE SHOP_FACTS
DROP CONSTRAINT FK_SHOP_FACTS_ARTICLE_LOOKUP;

--Drop OUTLET_LOOKUP FK
ALTER TABLE SHOP_FACTS
DROP CONSTRAINT FK_SHOP_FACTS_OUTLET_LOOKUP;

--Drop CALENDAR_YEAR_LOOKUP FK
ALTER TABLE SHOP_FACTS
DROP CONSTRAINT FK_SHOP_FACTS_CALENDAR_YEAR_LOOKUP;
