--Add FK in SHOP_FACTS

--Link with ARTICLE_COLOR_LOOKUP
ALTER TABLE SHOP_FACTS WITH CHECK
ADD CONSTRAINT FK_SHOP_FACTS_ARTICLE_COLOR_LOOKUP FOREIGN KEY (ARTICLE_CODE, COLOR_CODE)
REFERENCES ARTICLE_COLOR_LOOKUP(ARTICLE_CODE, COLOR_CODE);

--Link with ARTICLE_LOOKUP
ALTER TABLE SHOP_FACTS WITH CHECK
ADD CONSTRAINT FK_SHOP_FACTS_ARTICLE_LOOKUP FOREIGN KEY (ARTICLE_CODE)
REFERENCES ARTICLE_LOOKUP(ARTICLE_CODE);

--Link with OUTLET_LOOKUP
ALTER TABLE SHOP_FACTS WITH CHECK
ADD CONSTRAINT FK_SHOP_FACTS_OUTLET_LOOKUP FOREIGN KEY (SHOP_CODE)
REFERENCES OUTLET_LOOKUP(SHOP_CODE);

--Link with CALENDAR_YEAR_LOOKUP
ALTER TABLE SHOP_FACTS WITH CHECK
ADD CONSTRAINT FK_SHOP_FACTS_CALENDAR_YEAR_LOOKUP FOREIGN KEY (WEEK_KEY)
REFERENCES CALENDAR_YEAR_LOOKUP(WEEK_KEY);