-- Suppression des données
TRUNCATE TABLE SHOP_FACTS;
TRUNCATE TABLE OUTLET_LOOKUP;
TRUNCATE TABLE ARTICLE_COLOR_LOOKUP;
TRUNCATE TABLE ARTICLE_LOOKUP;
TRUNCATE TABLE CALENDAR_YEAR_LOOKUP;
-- Suppression des données dans les tables de rejet
TRUNCATE TABLE SHOP_FACTS_TREJ;
TRUNCATE TABLE OUTLET_LOOKUP_TREJ;
TRUNCATE TABLE ARTICLE_COLOR_LOOKUP_TREJ;
TRUNCATE TABLE ARTICLE_LOOKUP_TREJ;
TRUNCATE TABLE CALENDAR_YEAR_LOOKUP_TREJ;
-- Suppression des données dans les tables d'agrégations
TRUNCATE TABLE AGG_YR_QT_RN_ST_LN_CA_SR;
TRUNCATE TABLE AGG_YR_THRU_SN_SR_QT_MA;
-- Suppression des données dans les tables d'audit
TRUNCATE TABLE AUDIT_AUTO_ERRORS;
TRUNCATE TABLE AUDIT_AUTO_TRACE;
TRUNCATE TABLE AUDIT_DETAILS;
TRUNCATE TABLE AUDIT_ERRORS;
TRUNCATE TABLE AUDIT_TRACE;