--Create table ARTICLE_COLOR_LOOKUP_INC
CREATE TABLE ARTICLE_COLOR_LOOKUP_INC
(
ARTICLE_CODE NUMBER (6) ,
COLOR_CODE NUMBER (4) ,
ARTICLE_LABEL VARCHAR2 (45) ,
COLOR_LABEL VARCHAR2 (30) ,
CATEGORY VARCHAR2 (25) ,
SALE_PRICE NUMBER(8,2) ,
FAMILY_NAME VARCHAR2 (20) ,
FAMILY_CODE VARCHAR2 (3) ,
OPERATION_TYPE VARCHAR2 (6),
CONSTRAINT CHECK_OPERATION_TYPE_ACL CHECK (OPERATION_TYPE IN('INSERT','UPDATE','DELETE'))
);


--Create table ARTICLE_LOOKUP_INC
CREATE TABLE ARTICLE_LOOKUP_INC
(
ARTICLE_CODE NUMBER (6),
ARTICLE_LABEL VARCHAR2 (45) ,
CATEGORY VARCHAR2 (25) ,
SALE_PRICE NUMBER(8,2) ,
FAMILY_NAME VARCHAR2 (20) ,
FAMILY_CODE VARCHAR2 (3) ,
OPERATION_TYPE VARCHAR2 (6),
CONSTRAINT CHECK_OPERATION_TYPE_AL CHECK (OPERATION_TYPE IN('INSERT','UPDATE','DELETE'))
);

--Create table OUTLET_LOOKUP_INC
CREATE TABLE OUTLET_LOOKUP_INC
(
SHOP_NAME VARCHAR2 (30) ,
ADDRESS_1 VARCHAR2 (20) ,
MANAGER VARCHAR2 (10) ,
DATE_OPEN DATE ,
OPEN VARCHAR2 (1) ,
OWNED_OUTRIGHT VARCHAR2 (1) ,
FLOOR_SPACE NUMBER (4) ,
ZIP_CODE VARCHAR2 (6) ,
CITY VARCHAR2 (20) ,
STATE VARCHAR2 (20) ,
SHOP_CODE NUMBER (3) ,
OPERATION_TYPE VARCHAR2 (6),
CONSTRAINT CHECK_OPERATION_TYPE_OL CHECK (OPERATION_TYPE IN('INSERT','UPDATE','DELETE'))
) ;

--Create table CALENDAR_YEAR_LOOKUP_INC
CREATE TABLE CALENDAR_YEAR_LOOKUP_INC
(
WEEK_KEY NUMBER (3) NOT NULL ,
WEEK_IN_YEAR NUMBER (2) ,
YEAR NUMBER (4) ,
FISCAL_PERIOD VARCHAR2 (4) ,
YEAR_WEEK VARCHAR2 (7) ,
QUARTER NUMBER (1) ,
MONTH_NAME VARCHAR2 (10) ,
MONTH NUMBER (2) ,
HOLIDAY_FLAG VARCHAR2 (1) ,
OPERATION_TYPE VARCHAR2 (6),
CONSTRAINT CHECK_OPERATION_TYPE_CYL CHECK (OPERATION_TYPE IN('INSERT','UPDATE','DELETE'))
);

--Create table SHOP_FACTS_INC
CREATE TABLE SHOP_FACTS_INC
(
ID NUMBER (5) ,
ARTICLE_CODE NUMBER (6),
COLOR_CODE NUMBER (4),
WEEK_KEY NUMBER (3) ,
SHOP_CODE NUMBER (4),
MARGIN  NUMBER(13,2),
AMOUNT_SOLD  NUMBER(13,2),
QUANTITY_SOLD  NUMBER(13,2),
OPERATION_TYPE VARCHAR2 (6),
CONSTRAINT CHECK_OPERATION_TYPE_SF CHECK (OPERATION_TYPE IN('INSERT','UPDATE','DELETE'))
);