--Grant To emode

GRANT INSERT, UPDATE, DELETE ,SELECT
ON ARTICLE_COLOR_LOOKUP_INC
TO emode;

GRANT INSERT, UPDATE, DELETE ,SELECT
ON ARTICLE_LOOKUP_INC
TO emode;

GRANT INSERT, UPDATE, DELETE, SELECT
ON SHOP_FACTS_INC
TO emode;

GRANT INSERT, UPDATE, DELETE ,SELECT
ON OUTLET_LOOKUP_INC
TO emode;

GRANT INSERT, UPDATE, DELETE ,SELECT
ON CALENDAR_YEAR_LOOKUP_INC
TO emode;