CREATE TABLE AGG_YR_QT_RN_ST_LN_CA_SR
(
ID NUMERIC(5) IDENTITY(1,1) NOT NULL,
YEAR NUMERIC(4),
QUARTER VARCHAR(2),
STATE VARCHAR(20),
LINE VARCHAR(20),
CATEGORY VARCHAR(25),
SALES_REVENUE NUMERIC(13,2),
);

CREATE TABLE AGG_YR_THRU_SN_SR_QT_MA
(
ID NUMERIC(5) IDENTITY(1,1) NOT NULL,
YEAR NUMERIC(4),
QUARTER VARCHAR(2),
MONTH NUMERIC(2,0),
MONTH_NAME VARCHAR(10),
WEEK NUMERIC(2),
CITY VARCHAR(20),
STORE_NAME VARCHAR(30),
SALES_REVENUE NUMERIC(13,2),
QUANTITY_SOLD NUMERIC(13,2),
MARGIN NUMERIC(18,0)
);


ALTER TABLE AGG_YR_QT_RN_ST_LN_CA_SR
ADD CONSTRAINT PK_AGG_YR_QT_RN_ST_LN_CA_SR PRIMARY KEY (ID);

ALTER TABLE AGG_YR_THRU_SN_SR_QT_MA
ADD CONSTRAINT PK_AGG_YR_THRU_SN_SR_QT_MA PRIMARY KEY (ID);