-- Suppression de toutes les données ajoutées

DELETE FROM OUTLET_LOOKUP WHERE SHOP_CODE = 353;
DELETE FROM OUTLET_LOOKUP WHERE SHOP_CODE = 354;
DELETE FROM OUTLET_LOOKUP WHERE SHOP_CODE = 355;

DELETE FROM ARTICLE_LOOKUP WHERE ARTICLE_CODE = 189480;
DELETE FROM ARTICLE_LOOKUP WHERE ARTICLE_CODE = 189481;
DELETE FROM ARTICLE_LOOKUP WHERE ARTICLE_CODE = 189482;

DELETE FROM ARTICLE_COLOR_LOOKUP WHERE ARTICLE_CODE = 189480 AND COLOR_CODE = 901;
DELETE FROM ARTICLE_COLOR_LOOKUP WHERE ARTICLE_CODE = 189481 AND COLOR_CODE = 902;
DELETE FROM ARTICLE_COLOR_LOOKUP WHERE ARTICLE_CODE = 189482 AND COLOR_CODE = 902;

DELETE FROM SHOP_FACTS WHERE ID = 89172 ;
DELETE FROM SHOP_FACTS WHERE ID = 89173 ;
DELETE FROM SHOP_FACTS WHERE ID = 89174 ;
DELETE FROM SHOP_FACTS WHERE ID = 89175 ;

DELETE FROM CALENDAR_YEAR_LOOKUP WHERE WEEK_KEY = 263 ;
DELETE FROM CALENDAR_YEAR_LOOKUP WHERE WEEK_KEY = 264 ;

commit;